Pete - final changes to initial version of Capstone2 project website
redpath2312/MyCapstone2Website pull request #2
Opened 2023-11-02 21:33 UTC by redpath2312

Final tweaks meaning can merge into Master. May expand website in future eg About me section, and add more projects later on.

2023-11-24 15:07 UTC, algren123 requested changes
1. camel casing the classes, ids etc. or use dashes (mainImages vs main-images)
2. rewriting the CSS media queries so they encapsulate all the class logic into a single style.
3. rework/research Bootstrap columns and breakpoints (https://getbootstrap.com/docs/5.3/layout/columns/#column-breaks)

2023-11-24 15:07 UTC, algren123 commented on index.html
> +          <p class= "heroattribution">Image by <a href="https://www.freepik.com/free-vector/gamer-room-illustration_13558844.htm#query=simple%20game%20developer%20home%20desk&position=31&from_view=se
heroattribution -> heroAttribution

try and use camel casing when setting classes

2023-11-24 15:07 UTC, algren123 commented on index.html
> +              <img class= "mainimages" src = "images/programming-background-collage.jpg" alt = "web dev background">
same camel casing here

2023-11-24 15:07 UTC, algren123 commented on index.html
> +          <p class = "imageattribution">Image by <a href="https://www.freepik.com/free-photo/programming-background-collage_34089161.htm#query=website%20development&position=36&from_view=search&track
camel case here

2023-11-24 15:07 UTC, algren123 commented on index.html
> +              <img class= "mainimages" src = "images/game dev background.jpg" alt = "game dev background">
camel case here

2023-11-24 15:07 UTC, algren123 commented on css/style.css
> +      /*
commented code

2023-12-09 22:13 UTC, redpath2312 commented
The camel casing and media query rework done locally easy enough.
I can't remember the end goal of the column breaks and what the specific functionality /layout we were trying to get with them though i did find it finnicky, so guessing it was trying to make it simpler!?

2024-05-27 20:12 UTC, merged